name: sqlnotebook
on: [workflow_dispatch]
jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - run: curl -LO https://github.com/electroly/sqlnotebook/archive/refs/tags/v0.6.zip
      - run: unzip v0.6.zip
      - run: dir -name -recurse
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild "sqlnotebook-0.6\src\SqlNotebook.sln" /t:Build /v:q /nologo 
